CREATE DATABASE registry;
CREATE DATABASE validator;
CREATE DATABASE portal;

GRANT ALL PRIVILEGES ON DATABASE registry TO postgres;
GRANT ALL PRIVILEGES ON DATABASE validator TO postgres;
GRANT ALL PRIVILEGES ON DATABASE portal TO postgres;
