include:
  - path: ../postgres/docker-compose.yaml
    env_file: ../postgres/.env
  - path: ../keycloak/docker-compose.yaml
    env_file: ../keycloak/.env

services:
  registry:
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: ghcr.io/cirpass-2/mock-eu-registry-pgsql-oidc:latest
    ports:
      - "8082:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://postgres:5432/${POSTGRES_REGISTRY_DB}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 20
      QUARKUS_OIDC_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_URL}
      QUARKUS_OIDC_CLIENT_ID: ${REGISTRY_CLIENT_ID}
      QUARKUS_OIDC_TOKEN_ISSUER: ${KEYCLOAK_TOKEN_ISSUER}
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${REGISTRY_CLIENT_SECRET}
      AUTOCOMPLETION_ENABLED_FOR: commodityCode,facilitiesId
      REGISTRY_UPDATE_STRATEGY: MODIFY
      REGISTRY_REOID_FROM_CLAIM_ENABLED: 'true'
      REGISTRY_DPP_VALIDATION_ENABLED: 'true'
      QUARKUS_REST_CLIENT_DPP_VALIDATION_URL: http://validator:8080
      QUARKUS_OIDC_DISCOVERY_ENABLED: "false"
      QUARKUS_OIDC_JWKS_PATH: http://keycloak:8180/realms/cirpass-2/protocol/openid-connect/certs
  

  validator:
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: ghcr.io/cirpass-2/dpp-validator-pgsql-oidc:latest
    ports:
      - "8083:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://postgres:5432/${POSTGRES_VALIDATOR_DB}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 20
      QUARKUS_OIDC_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_URL}
      QUARKUS_OIDC_TOKEN_ISSUER: ${KEYCLOAK_TOKEN_ISSUER}
      QUARKUS_OIDC_CLIENT_ID: ${VALIDATOR_CLIENT_ID}
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${VALIDATOR_CLIENT_SECRET}
      QUARKUS_OIDC_DISCOVERY_ENABLED: "false"
      QUARKUS_OIDC_JWKS_PATH: http://keycloak:8180/realms/cirpass-2/protocol/openid-connect/certs
      QUARKUS_LOG_CATEGORY__IO_QUARKUS_OIDC__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__IO_QUARKUS_SECURITY__LEVEL: DEBUG

  data-extractor:
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: ghcr.io/cirpass-2/dpp-data-extractor-pgsql-oidc:latest
    ports:
      - "8084:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://postgres:5432/${POSTGRES_REGISTRY_DB}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 20
      QUARKUS_DATASOURCE_EXTRACTION_REACTIVE_URL: vertx-reactive:postgresql://postgres:5432/${POSTGRES_PORTAL_DB}
      QUARKUS_DATASOURCE_EXTRACTION_USERNAME: ${POSTGRES_USER}
      QUARKUS_DATASOURCE_EXTRACTION_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_EXTRACTION_REACTIVE_MAX_SIZE: 20
      QUARKUS_OIDC_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_URL}
      QUARKUS_OIDC_TOKEN_ISSUER: ${KEYCLOAK_TOKEN_ISSUER}
      QUARKUS_OIDC_CLIENT_ID: ${RENDERER_CLIENT_ID}
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${RENDERER_CLIENT_SECRET}
      QUARKUS_HTTP_CORS_ORIGINS: ${CORS_ORIGINS}
      QUARKUS_OIDC_DISCOVERY_ENABLED: "false"
      QUARKUS_OIDC_JWKS_PATH: http://keycloak:8180/realms/cirpass-2/protocol/openid-connect/certs
      EXTRACTOR_DPP_REFERENCE_ONTOLOGY_VOCABULARIES: https://w3id.org/eudpp#,https://w3id.org/eudpp

  renderer-be:
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: ghcr.io/cirpass-2/dpp-renderer-be-pgsql-oidc:latest
    ports:
      - "8085:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://postgres:5432/${POSTGRES_PORTAL_DB}
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE: 20
      QUARKUS_OIDC_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_URL}
      QUARKUS_OIDC_TOKEN_ISSUER: ${KEYCLOAK_TOKEN_ISSUER}
      QUARKUS_OIDC_CLIENT_ID: ${RENDERER_CLIENT_ID}
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${RENDERER_CLIENT_SECRET}
      QUARKUS_HTTP_CORS_ORIGINS: ${CORS_ORIGINS}
      QUARKUS_VERTX_MAX_EVENT_LOOP_EXECUTE_TIME: 10
      QUARKUS_VERTX_MAX_EVENT_LOOP_EXECUTE_TIME_UNIT: SECONDS
      QUARKUS_OIDC_DISCOVERY_ENABLED: "false"
      QUARKUS_OIDC_JWKS_PATH: http://keycloak:8180/realms/cirpass-2/protocol/openid-connect/certs
  renderer-fe:
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      keycloak:
        condition: service_healthy
      renderer-be:
        condition: service_started
      data-extractor:
        condition: service_started
    image: ghcr.io/cirpass-2/dpp-renderer-fe:latest
    ports:
      - "4200:8080"
    environment:
      BACKEND_URL: ${BACKEND_URL}
      CAPABILITIES_URL: ${CAPABILITIES_URL}
      OIDC_ISSUER: ${FE_OIDC_ISSUER}
      OIDC_CLIENT_ID: ${FE_OIDC_CLIENT_ID}
      OIDC_HTTPS: ${FE_OIDC_HTTPS}
